.docker_build_template: &docker_build_definition # YAML anchor for re-use
  stage: distribute # Default stage, can be overridden
  image: docker:latest
  script:
    - |
      echo "Waiting for docker daemon..."
      timeout 30 sh -c 'while ! docker info > /dev/null 2>&1; do echo -n "."; sleep 1; done;'
      echo "Docker daemon is ready!"
    - docker info
    - echo "Logging in to GitLab Container Registry: $CI_REGISTRY_HOST"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY_HOST
    # IMAGE_NAME and DOCKERFILE_PATH must be defined in the job using this template
    - echo "Building Docker image $IMAGE_NAME from $DOCKERFILE_PATH"
    - docker build -t $IMAGE_NAME:latest --file $DOCKERFILE_PATH .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - echo "Pushing image to registry: $IMAGE_NAME"
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
