name: Python Formatter
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'

jobs:
  python_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Run Black
        uses: https://git.jonahmakowski.ca/custom_actions/format-python@main
        with:
          script-path: 'jonahmakowski/pyWrskp'
