name: Python Formatter
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'

jobs:
  python_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          pip-version: '25.x'

      - name: Install dependencies
        run: |
          pip install black
          git config --global user.email "forgejo-actions@localhost"
          git config --global user.name "Forgejo Actions"

      - name: Run Black
        run: |
          echo "Running Black..."
          black .
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Auto-format Python code" || echo "Nothing to commit"
            git push https://$FORGEJO_TOKEN@github.com/jonahmakowski/pyWrskp.git main
          fi
