name: Rust Formatter
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  rust_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Formatter
        uses: https://git.jonahmakowski.ca/custom_actions/format-rust@main
        with:
          repo: 'jonahmakowski/pyWrskp'
