class SudokuSolver:
    def __init__(self):
        self.board = {'row1': {'colum1': '',
                               'colum2': '',
                               'colum3': 2,
                               'colum4': '',
                               'colum5': '',
                               'colum6': 4,
                               'colum7': 1,
                               'colum8': 6,
                               'colum9': ''},

                      'row2': {'colum1': '',
                               'colum2': 5,
                               'colum3': '',
                               'colum4': '',
                               'colum5': '',
                               'colum6': '',
                               'colum7': '',
                               'colum8': 3,
                               'colum9': ''},

                      'row3': {'colum1': 4,
                               'colum2': '',
                               'colum3': 8,
                               'colum4': '',
                               'colum5': '',
                               'colum6': 6,
                               'colum7': 2,
                               'colum8': '',
                               'colum9': 9},

                      'row4': {'colum1': '',
                               'colum2': 4,
                               'colum3': 3,
                               'colum4': '',
                               'colum5': 7,
                               'colum6': 8,
                               'colum7': 5,
                               'colum8': '',
                               'colum9': 2},

                      'row5': {'colum1': '',
                               'colum2': 8,
                               'colum3': '',
                               'colum4': 2,
                               'colum5': '',
                               'colum6': '',
                               'colum7': 6,
                               'colum8': 7,
                               'colum9': 3},

                      'row6': {'colum1': '',
                               'colum2': 6,
                               'colum3': '',
                               'colum4': 1,
                               'colum5': '',
                               'colum6': '',
                               'colum7': 9,
                               'colum8': 8,
                               'colum9': ''},

                      'row7': {'colum1': 5,
                               'colum2': '',
                               'colum3': 4,
                               'colum4': 8,
                               'colum5': '',
                               'colum6': 3,
                               'colum7': 7,
                               'colum8': 2,
                               'colum9': 6},

                      'row8': {'colum1': '',
                               'colum2': '',
                               'colum3': 6,
                               'colum4': '',
                               'colum5': '',
                               'colum6': '',
                               'colum7': '',
                               'colum8': '',
                               'colum9': 5},

                      'row9': {'colum1': 8,
                               'colum2': '',
                               'colum3': '',
                               'colum4': 5,
                               'colum5': 6,
                               'colum6': 7,
                               'colum7': 3,
                               'colum8': '',
                               'colum9': 1}}
    def check(self):