words = ['actor', 'angry', 'answer', 'ape', 'baby', 'backwards', 'banana', 'baseball', 'blood', 
         'captain', 'card', 'cat', 'chair', 'checkers', 'cheese', 'children', 'circle', 'coal', 
         'coffee', 'copper', 'cord', 'corner', 'cotton', 'cloud','daughter', 'door', 'drain', 'drug', 
         'ears', 'expert', 'fan', 'finger', 'force', 'front', 'garden', 'girls', 'glove', 'goal', 
         'goldfish', 'grandmother', 'group', 'hands', 'hearing', 'heaven', 'hockey', 'hole', 'honey', 
         'hope', 'ice', 'iron', 'jam', 'jellyfish', 'kick', 'kitchen', 'knee', 'leader', 
         'lizards', 'mail', 'market', 'melon', 'mint', 'mitten', 'mountain', 'name', 'nation', 
         'needle', 'nest', 'oatmeal', 'office', 'orange', 'pear', 'pets', 'picture', 'rake',
         'rest', 'river', 'rock','room', 'rub', 'sand', 'saucer', 'scarf', 'scissors','season',
         'seat', 'shark', 'side', 'siren', 'skate', 'space', 'spot', 'steam', 'stew', 'sticks',
         'stop', 'sugar', 'sunrise', 'surprise', 'table', 'talk', 'thread', 'tongue', 
         'toothbrush', 'turkey', 'unicorn', 'village', 'vision', 'wash', 'water', 'wool', 'worm', 
         'wrench','yellow']
