name: Python Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 2.*
          - 3.0.*
          - 3.1.*
          - 3.2.*
          - 3.3.*
          - 3.4.*
          - 3.5.*
          - 3.6.*
          - 3.7.*
          - 3.8.*
          - 3.9.*
          - 3.10.*
          - 3.11.*

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests -p "test_*.py"
